In [1]:
from numpy import random

In [2]:
import numpy as np

In [3]:
#uniform random numbers [1,0]
dataOne = random.rand(5,5)

In [4]:
np.mean(dataOne)

0.6050695286351132

In [5]:
print(dataOne)

[[0.6817485  0.09820936 0.05828214 0.73307317 0.50479197]
 [0.75802244 0.71180727 0.73331387 0.44430347 0.74893934]
 [0.71371593 0.63660502 0.76020247 0.64011967 0.25030036]
 [0.7432402  0.39884037 0.65289054 0.68759415 0.82027616]
 [0.97637518 0.40030537 0.75744425 0.50339949 0.71293753]]


In [6]:
print('I love data science')

I love data science


In [7]:
variableName =25

In [8]:
variableName1 = 'I love data science'

In [9]:
print(variableName1)

I love data science


In [10]:
type(variableName)

int

In [11]:
varibaleName = 2.5

In [12]:
type(variableName)

int

In [13]:
varibaleName = 25.0

In [14]:
type(varibaleName)

float

In [15]:
varOne =25

In [16]:
varTwo = 25.0

In [17]:
varThree = varOne + varTwo

In [18]:
print(varThree)

50.0


In [19]:
varOne =25

In [20]:
varTwo = 'Hello'

In [21]:
varThree = varOne + varTwo

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [22]:
print(varThree)

50.0


In [23]:
listName = []

In [24]:
listOne =[1,2,3,4]

In [25]:
print(listOne[1:3])

[2, 3]


In [26]:
tel = {'jack':4098, 'sape':4139}

In [27]:
tel['jack']

4098

In [28]:
ownDic =[1,2,3,4,5]

In [29]:
import math as m

In [30]:
m.sqrt(ownDic[0])

1.0